spring:
  web:
    cors:
      allowed-origins: http://localhost:4200
  application:
    name: dishmaster
  data:
    elasticsearch:
      cluster-name: dishmaster
      cluster-nodes: localhost:9200
      repositories:
        enabled: true
springdoc:
  swagger-ui:
    path: /api/swagger-ui
  api-docs:
    path: /v3/dish-master-api-docs
server:
  port: 8080